model:
  num_encoder_layers: 6
  num_encoder_heads: 8
  num_decoder_layers: 6
  num_decoder_heads: 8
  d_model: 512
  encoder_ffn_dim: 2048
  decoder_ffn_dim: 2048
  max_sequence_length: 512
  
train:
  output_dir: results/prod_problem/GF7_n=2_short
  num_train_epochs: 32
  learning_rate: 5e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  batch_size: 128
  test_batch_size: 128
  lr_scheduler_type: "linear"
  max_grad_norm: 1.0
  optimizer: adamw_torch
  num_workers: 4
  seed: 42


# dataset path
train_dataset_path: data/part_prod_problem/GF7_n=2/train_raw.txt
test_dataset_path: data/part_prod_problem/GF7_n=2/test_raw.txt
# problem config
num_variables: 2
max_degree: 10
max_coeff: 7
field: GF7