vocab:
  - "[C]"
  - "C-50"
  - "C-49"
  - "C-48"
  - "C-47"
  - "C-46"
  - "C-45"
  - "C-44"
  - "C-43"
  - "C-42"
  - "C-41"
  - "C-40"
  - "C-39"
  - "C-38"
  - "C-37"
  - "C-36"
  - "C-35"
  - "C-34"
  - "C-33"
  - "C-32"
  - "C-31"
  - "C-30"
  - "C-29"
  - "C-28"
  - "C-27"
  - "C-26"
  - "C-25"
  - "C-24"
  - "C-23"
  - "C-22"
  - "C-21"
  - "C-20"
  - "C-19"
  - "C-18"
  - "C-17"
  - "C-16"
  - "C-15"
  - "C-14"
  - "C-13"
  - "C-12"
  - "C-11"
  - "C-10"
  - "C-9"
  - "C-8"
  - "C-7"
  - "C-6"
  - "C-5"
  - "C-4"
  - "C-3"
  - "C-2"
  - "C-1"
  - "C0"
  - "C1"
  - "C2"
  - "C3"
  - "C4"
  - "C5"
  - "C6"
  - "C7"
  - "C8"
  - "C9"
  - "C10"
  - "C11"
  - "C12"
  - "C13"
  - "C14"
  - "C15"
  - "C16"
  - "C17"
  - "C18"
  - "C19"
  - "C20"
  - "C21"
  - "C22"
  - "C23"
  - "C24"
  - "C25"
  - "C26"
  - "C27"
  - "C28"
  - "C29"
  - "C30"
  - "C31"
  - "C32"
  - "C33"
  - "C34"
  - "C35"
  - "C36"
  - "C37"
  - "C38"
  - "C39"
  - "C40"
  - "C41"
  - "C42"
  - "C43"
  - "C44"
  - "C45"
  - "C46"
  - "C47"
  - "C48"
  - "C49"
  - "C50"
  - "E0"
  - "E1"
  - "E2"
  - "E3"
  - "E4"
  - "E5"
  - "[SEP]"
special_vocab:
  pad_token: "[PAD]"
  bos_token: "<s>"
  eos_token: "</s>"
  cls_token: "[CLS]" 